apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: sealed-secrets
      version: "2.17.3"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
