apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - monitoring-namespace.yaml
    - prometheus-community-repo.yaml
    - grafana-repo.yaml
    - prometheus-stack-release.yaml
    - grafana-ingress-class.yaml
    - grafana-ingress.yaml