# clusters/my-cluster/infra/01-core-infra/ingress-nginx/kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets-infra
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/my-cluster/infra/core-infra/sealed-secrets/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: sealed-secrets
      namespace: kube-system