apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-root
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/my-cluster/infra/core-infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system