apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-root
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/my-cluster/infra/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # 핵심 인프라가 먼저 배포되고 그 다음 모니터링이 배포되도록 의존성 설정
  dependsOn:
    - name: core-infra