# clusters/my-cluster/infra/openebs-storage.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: openebs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebs-maya-operator
  namespace: openebs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openebs-maya-operator
rules:
- apiGroups: ["*"]
  resources: ["nodes", "nodes/proxy"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["namespaces", "services", "pods", "deployments", "events", "endpoints", "configmaps", "secrets", "jobs", "storageclasses", "persistentvolumeclaims", "persistentvolumes"]
  verbs: ["*"]
- apiGroups: ["openebs.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openebs-maya-operator
subjects:
- kind: ServiceAccount
  name: openebs-maya-operator
  namespace: openebs
roleRef:
  kind: ClusterRole
  name: openebs-maya-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openebs-localpv-provisioner
  namespace: openebs
  labels:
    app: openebs-localpv-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openebs-localpv-provisioner
  template:
    metadata:
      labels:
        app: openebs-localpv-provisioner
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
        - name: openebs-localpv-provisioner
          image: openebs/provisioner-localpv:3.3.0
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OPENEBS_NAMESPACE
              value: openebs
            - name: OPENEBS_SERVICE_ACCOUNT
              value: openebs-maya-operator
            - name: OPENEBS_IO_BASE_PATH
              value: /var/openebs/local
          volumeMounts:
            - mountPath: /var/openebs/local
              name: openebs-hostpath
      volumes:
        - name: openebs-hostpath
          hostPath:
            path: /var/openebs/local
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-hostpath
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/var/openebs/local/"
    # 이 StorageClass를 클러스터의 기본값으로 설정합니다.
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
