# clusters/my-cluster/infra/01-core-infra/local-path-storage/kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-storage-infra
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/my-cluster/infra/core-infra/storage/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: openebs-localpv-provisioner
      namespace: openebs