apiVersion: kustomize.toolkit.fluxcd.io/v1 # FluxCD Custom Resource (CR)
kind: Kustomization
metadata:
  name: core-infra # 'infra-root' Kustomization에서 dependsOn으로 참조할 이름
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/my-cluster/infra/core-infra # 이 Kustomization의 Git 저장소 내 경로
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Cert-Manager, Ingress-Nginx, Local-Path-Storage는 서로 병렬로 배포 가능
  # (각 컴포넌트 내부에서 CRD와 Release 순서를 관리)
  dependsOn:
    - name: cert-manager-infra # Cert-Manager Kustomization이 먼저
    - name: ingress-nginx-infra # Ingress-Nginx Kustomization이 먼저
    - name: local-path-storage-infra # Local Path Storage Kustomization이 먼저
  resources:
    - ./cert-manager
    - ./ingress-nginx
    - ./storage
  healthChecks: # 핵심 인프라 컴포넌트가 모두 준비되었는지 확인 (선택 사항이지만 강력 권장)
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-webhook # Cert-Manager 웹훅 배포 (실제 배포명 확인 필요)
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-controller # Ingress-Nginx 컨트롤러 배포 (실제 배포명 확인 필요)
      namespace: ingress-nginx # 또는 ingress-nginx가 설치되는 네임스페이스