apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  
  # 'helm install --set' 또는 '--values'에 해당하는 부분입니다.
  # 로드밸런서 없는 환경을 위해 HostPort 모드로 설정합니다.
  values:
    controller:
      # Controller를 DaemonSet으로 배포하여 모든 노드에 하나씩 실행합니다.
      kind: DaemonSet
      # HostPort를 사용하므로 별도의 LoadBalancer/NodePort 서비스는 비활성화합니다.
      service:
        enabled: false
      # HostPort를 활성화하여 노드의 80, 443 포트를 직접 사용합니다.
      hostPort:
        enabled: true