apiVersion: batch/v1
kind: Job
metadata:
  # 잡의 이름 (매번 실행 시 고유해야 할 경우 'data-seed-job-{{ a-random-string }}' 처럼 사용)
  name: data-seed-job
  namespace: default
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 2
  template:
    spec:
      volumes:
        - name: oci-secret-volume
          secret:
            secretName: oci-credentials
      containers:
        - name: data-seeder
          image: ghcr.io/jth0809/personal_project/backend:439752c
          args: ["--init-data"]
          volumeMounts:
            - name: oci-secret-volume
              mountPath: "/etc/oci"
              readOnly: true
          envFrom:
            - secretRef:
                name: db-credentials
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: oci-info
            - secretRef:
                name: oauth-secret
            - secretRef:
                name: payments-secret-backend
          env:
            - name: SPRING_MAIN_WEB_APPLICATION_TYPE
              value: "NONE"
      restartPolicy: OnFailure
