apiVersion: batch/v1
kind: Job
metadata:
  # 잡의 이름 (매번 실행 시 고유해야 할 경우 'data-seed-job-{{ a-random-string }}' 처럼 사용)
  name: data-seed-job
  namespace: default
spec:
  # 성공할 때까지 재시도하는 횟수
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: data-seeder
          image: ghcr.io/jth0809/personal_project/backend:82ea124
          args: ["--init-data"]
          envFrom:
            - secretRef:
                name: db-credentials
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: oci-info
          env:
            - name: SPRING_MAIN_WEB_APPLICATION_TYPE
              value: "NONE"
      restartPolicy: OnFailure
