# clusters/my-cluster/backend.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      automountServiceAccountToken: false
      containers:
        - name: backend
          image: ghcr.io/jth0809/personal_project/backend:0c42f1e
          volumeMounts:
            - name: oci-secret-volume
              mountPath: "/etc/oci"
              readOnly: true
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: db-credentials
            - secretRef:
                name: jwt-secret
            - secretRef:
                name: oci-info
            - secretRef:
                name: oauth-secret
            - secretRef:
                name: payments-secret-backend
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
      volumes:
        - name: oci-secret-volume
          secret:
            secretName: oci-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc # 서비스 이름
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
