apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-prod
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    email: jth0809@naver.com
    privateKeySecretRef:
      name: zerossl-prod-private-key
    externalAccountBinding:
      keyID: nEYmB15HKxhatraO2PbN5g
      keySecretRef:
        name: zerossl-hmac-secret
        key: hmacKey
    solvers:
    - http01:
        ingress:
          class: nginx
