# clusters/my-cluster/infra/02-monitoring/prometheus-stack/kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-stack-infra
  namespace: flux-system
spec:
  interval: 30m
  path: ./clusters/my-cluster/infra/monitoring/prometheus-stack/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment # Grafana가 정상적으로 배포되었는지 확인
      name: kube-prometheus-stack-grafana
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment # Prometheus Operator가 정상적으로 배포되었는지 확인
      name: kube-prometheus-stack-operator
      namespace: monitoring
    - apiVersion: apps/v1
      kind: StatefulSet # Prometheus 본체가 정상적으로 배포되었는지 확인
      name: prometheus-kube-prometheus-stack-prometheus
      namespace: monitoring
    - apiVersion: apps/v1
      kind: StatefulSet # Alertmanager가 정상적으로 배포되었는지 확인
      name: alertmanager-kube-prometheus-stack-alertmanager
      namespace: monitoring