# clusters/my-cluster/infra/openebs-storage.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: openebs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebs-maya-operator
  namespace: openebs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openebs-maya-operator
rules:
- apiGroups: ["*"]
  resources: ["nodes", "nodes/proxy"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["namespaces", "services", "pods", "deployments", "events", "endpoints", "configmaps", "secrets", "jobs", "storageclasses", "persistentvolumeclaims", "persistentvolumes"]
  verbs: ["*"]
- apiGroups: ["openebs.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openebs-maya-operator
subjects:
- kind: ServiceAccount
  name: openebs-maya-operator
  namespace: openebs
roleRef:
  kind: ClusterRole
  name: openebs-maya-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openebs-localpv-provisioner
  namespace: openebs
  labels:
    app: openebs-localpv-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openebs-localpv-provisioner
  template:
    metadata:
      labels:
        app: openebs-localpv-provisioner
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
        - name: openebs-localpv-provisioner
          image: openebs/provisioner-localpv:4.3.2
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OPENEBS_NAMESPACE
              value: openebs
            - name: OPENEBS_SERVICE_ACCOUNT
              value: openebs-maya-operator
            - name: OPENEBS_IO_BASE_PATH
              value: /var/openebs/local
          resources: # <--- 이 부분을 추가해야 합니다.
            requests:
              memory: "100Mi" # 최소 메모리 요청
              cpu: "50m"      # 최소 CPU 요청 (50 millicores = 0.05 CPU 코어)
            limits:
              memory: "200Mi" # 최대 메모리 사용 제한
              cpu: "100m"     # 최대 CPU 사용 제한
          volumeMounts:
            - mountPath: /var/openebs/local
              name: openebs-hostpath
      volumes:
        - name: openebs-hostpath
          hostPath:
            path: /var/openebs/local
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-hostpath
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/var/openebs/local/"
    # 이 StorageClass를 클러스터의 기본값으로 설정합니다.
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
