# clusters/my-cluster/infra/01-core-infra/cert-manager/kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-infra
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/my-cluster/infra/core-infra/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  resources:
    - cert-manager-namespace.yaml
    - jetstack-repo.yaml
    - cert-manager-release.yaml
    - zerossl-cluster-issuer.yaml
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-cainjector
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-webhook
      namespace: cert-manager